### ISSUE TITLE
Test RMLSTC0007c failing

### ISSUE THREAD

**Issue by idomingu** [kg-construct/BURP#4]
Hi,

While trying out some of the test cases in BURP I noticed **RMLSTC0007c** test case fails with the following error:

```
java.lang.RuntimeException: javax.xml.xpath.XPathExpressionException: javax.xml.transform.TransformerException: A location step was expected following the '/' or '//' token.
        at burp.ls.XMLSource.iterator(XMLSource.java:48)
        at burp.Main.generate(Main.java:84)
        at burp.Main.doMain(Main.java:56)
        at burp.Main.main(Main.java:43)
Caused by: javax.xml.xpath.XPathExpressionException: javax.xml.transform.TransformerException: A location step was expected following the '/' or '//' token.
        at java.xml/com.sun.org.apache.xpath.internal.jaxp.XPathImpl.compile(Unknown Source)
        at burp.ls.XMLSource.iterator(XMLSource.java:39)
        ... 3 more
Caused by: javax.xml.transform.TransformerException: A location step was expected following the '/' or '//' token.
        at java.xml/com.sun.org.apache.xpath.internal.compiler.XPathParser.error(Unknown Source)
        at java.xml/com.sun.org.apache.xpath.internal.compiler.XPathParser.RelativeLocationPath(Unknown Source)
        at java.xml/com.sun.org.apache.xpath.internal.compiler.XPathParser.LocationPath(Unknown Source)
        at java.xml/com.sun.org.apache.xpath.internal.compiler.XPathParser.PathExpr(Unknown Source)
        at java.xml/com.sun.org.apache.xpath.internal.compiler.XPathParser.UnionExpr(Unknown Source)
        at java.xml/com.sun.org.apache.xpath.internal.compiler.XPathParser.UnaryExpr(Unknown Source)
        at java.xml/com.sun.org.apache.xpath.internal.compiler.XPathParser.MultiplicativeExpr(Unknown Source)
        at java.xml/com.sun.org.apache.xpath.internal.compiler.XPathParser.AdditiveExpr(Unknown Source)
        at java.xml/com.sun.org.apache.xpath.internal.compiler.XPathParser.RelationalExpr(Unknown Source)
        at java.xml/com.sun.org.apache.xpath.internal.compiler.XPathParser.EqualityExpr(Unknown Source)
        at java.xml/com.sun.org.apache.xpath.internal.compiler.XPathParser.AndExpr(Unknown Source)
        at java.xml/com.sun.org.apache.xpath.internal.compiler.XPathParser.OrExpr(Unknown Source)
        at java.xml/com.sun.org.apache.xpath.internal.compiler.XPathParser.Expr(Unknown Source)
        at java.xml/com.sun.org.apache.xpath.internal.compiler.XPathParser.initXPath(Unknown Source)
        at java.xml/com.sun.org.apache.xpath.internal.XPath.<init>(Unknown Source)
        ... 5 more
javax.xml.xpath.XPathExpressionException: javax.xml.transform.TransformerException: A location step was expected following the '/' or '//' token.
System exiting with code: 1
```
Test was executed only with the ```--mappingFile``` argument. 

Is this the expected behavior?

Many thanks!

**Comment by chrdebru** [comment]
Hello,

Thanks for pointing this out. This test fell through the cracks because some failed ("source not yet implemented").

RMLSTC0007c failed because : 

- The iterator is incorrect: it should have been `//Friends/Character` instead of `//Friends/Character/`
- The selector for the attribute was also incorrect: is should have been `@id` instead of `id`

I have committed fixes to the test case.

@DylanVanAssche: here are some problems in RMLSTC0007c and RMLSTC0007d.

With my best regards,

Christophe

**Comment by chrdebru** [comment]
@idomingu Let me know if this is OK and I will then close the issue.

**Comment by idomingu** [comment]
Hi @chrdebru, it's working now. Thanks!

**Comment by DylanVanAssche** [comment]
Test case also fixed upstream, closing! Thanks!
